# file: roles/base_osx/tasks/common.yml

---
- name: common | brew update 1
  homebrew: update_homebrew=yes
  ignore_errors: True

- name: common | brew tap base_osx_common.taps
  homebrew_tap: name={{ item }} state=present
  with_items: base_osx.common.taps
  ignore_errors: True

- name: common | brew update 2
  homebrew: update_homebrew=yes upgrade_all=yes
  ignore_errors: True

- local_action: osx_say msg="Installing Homebrew packages."

- name: common | brew install base_osx.common.packages
  homebrew: name={{ item }} state=upgraded
  with_items: base_osx.common.packages
  ignore_errors: True

- local_action: osx_say msg="Homebrew packages have been installed. Brew cask may require a super-user password."

- name: common | brew cask install base_osx.common.casks
  homebrew_cask: name={{ item }} state=installed
  with_items: base_osx.common.casks
  ignore_errors: True

- local_action: osx_say msg="Casks have been installed."
