# file: roles/base_osx/tasks/preferences.yml
# See https://github.com/mathiasbynens/dotfiles/blob/master/.osx

---
- include: preferences/general.yml
- include: preferences/userinput.yml
- include: preferences/ui.yml
- include: preferences/finder.yml
- include: preferences/dock.yml
- include: preferences/safari.yml
- include: preferences/mail.yml
- include: preferences/spotlight.yml
- include: preferences/terminal.yml
- include: preferences/iterm.yml
- include: preferences/timemachine.yml
- include: preferences/activitymon.yml
- include: preferences/utils.yml
- include: preferences/appstore.yml
- include: preferences/messages.yml
- include: preferences/googlechrome.yml
- include: preferences/gpgmail2.yml
- include: preferences/transmission.yml
- include: preferences/twitter.yml

- name: Kill affected applications (some of these changes require a logout/restart to take effect)
  shell: "killall {{ item }} > /dev/null 2<&1"
  ignore_errors: yes
  with_items:
    - Activity Monitor
    - Address Book
    - Calendar
    - Contacts
    - cfprefsd
    - Dock
    - Finder
    - Google Chrome
    - Google Chrome Canary
    - Mail
    - Messages
    - Safari
    - SystemUIServer
    - Terminal
    - Transmission
    - Twitter
    - iCal
