---
# finder ------------------------------------------------------------------ {{{
- name: Finder - allow quitting via ⌘ + Q; doing so will also hide desktop icons
  command: "defaults write com.apple.finder QuitMenuItem -bool true"

- name: Finder - disable window animations and Get Info animations
  command: "defaults write com.apple.finder DisableAllAnimations -bool true"

- name: Set Desktop as the default location for new Finder windows
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.finder NewWindowTarget -string 'PfLo'"
    - "defaults write com.apple.finder NewWindowTargetPath -string 'file://${HOME}/Desktop/'"

- name: Show icons for hard drives, servers, and removable media on the desktop
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true"
    - "defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true"
    - "defaults write com.apple.finder ShowMountedServersOnDesktop -bool true"
    - "defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true"

- name: Finder - show hidden files by default
  command: "defaults write com.apple.finder AppleShowAllFiles -bool true"

- name: Finder - show all filename extensions
  command: "defaults write NSGlobalDomain AppleShowAllExtensions -bool true"

- name: Finder - show status bar
  command: "defaults write com.apple.finder ShowStatusBar -bool true"

- name: Finder - show path bar
  command: "defaults write com.apple.finder ShowPathbar -bool true"

- name: Finder - allow text selection in Quick Look
  command: "defaults write com.apple.finder QLEnableTextSelection -bool true"

- name: Display full POSIX path as Finder window title
  command: "defaults write com.apple.finder _FXShowPosixPathInTitle -bool true"

- name: When performing a search, search the current folder by default
  command: "defaults write com.apple.finder FXDefaultSearchScope -string 'SCcf'"

- name: Disable the warning when changing a file extension
  command: "defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false"

- name: Enable spring loading for directories
  command: "defaults write NSGlobalDomain com.apple.springing.enabled -bool true"

- name: Remove the spring loading delay for directories
  command: "defaults write NSGlobalDomain com.apple.springing.delay -float 0"

- name: Avoid creating .DS_Store files on network volumes
  command: "defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true"

- name: Disable disk image verification
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.frameworks.diskimages skip-verify -bool true"
    - "defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true"
    - "defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true"

- name: Automatically open a new Finder window when a volume is mounted
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true"
    - "defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true"
    - "defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true"

- name: Show item info near icons on the desktop and in other icon views
  command: "{{ item }}"
  with_items:
    - "/usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:showItemInfo true' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"
    #- "/usr/libexec/PlistBuddy -c 'Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"
    - "/usr/libexec/PlistBuddy -c 'Set :StandardViewSettings:IconViewSettings:showItemInfo true' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"

- name: Show item info to the right of the icons on the desktop
  command: "/usr/libexec/PlistBuddy -c 'Set DesktopViewSettings:IconViewSettings:labelOnBottom false' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  command: "{{ item }}"
  with_items:
    - "/usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:arrangeBy grid' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"
    #- "/usr/libexec/PlistBuddy -c 'Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"
    - "/usr/libexec/PlistBuddy -c 'Set :StandardViewSettings:IconViewSettings:arrangeBy grid' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"

- name: Increase grid spacing for icons on the desktop and in other icon views
  command: "{{ item }}"
  with_items:
    - "/usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:gridSpacing 100' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"
    #- "/usr/libexec/PlistBuddy -c 'Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 100' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"
    - "/usr/libexec/PlistBuddy -c 'Set :StandardViewSettings:IconViewSettings:gridSpacing 100' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"

- name: Increase the size of icons on the desktop and in other icon views
  command: "{{ item }}"
  with_items:
    - "/usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:iconSize 80' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"
    #- "/usr/libexec/PlistBuddy -c 'Set :FK_StandardViewSettings:IconViewSettings:iconSize 80' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"
    - "/usr/libexec/PlistBuddy -c 'Set :StandardViewSettings:IconViewSettings:iconSize 80' {{ smt.home}}/Library/Preferences/com.apple.finder.plist"

- name: Use list view in all Finder windows by default
  command: "defaults write com.apple.finder FXPreferredViewStyle -string 'Nlsv'"

- name: Disable the warning before emptying the Trash
  command: "defaults write com.apple.finder WarnOnEmptyTrash -bool false"

- name: Empty Trash securely by default
  command: "defaults write com.apple.finder EmptyTrashSecurely -bool true"

- name: Enable AirDrop over Ethernet and on unsupported Macs running Lion
  command: "defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true"

# - name: Enable the MacBook Air SuperDrive on any Mac
#   shell: "sudo nvram boot-args='mbasd=1'"

- name: Show the ~/Library folder
  command: "chflags nohidden {{ smt.home}}/Library"

# - name: Remove Dropbox’s green checkmark icons in Finder
#   shell: >
#     file=/Applications/Dropbox.app/Contents/Resources/emblem-dropbox-uptodate.icns
#     [ -e '${file}' ] && mv -f '${file}' '${file}.bak'

- name: Expand `General`, `Open With`, and `Sharing & Permissions` panes in File Info
  command: "defaults write com.apple.finder FXInfoPanesExpanded -dict General -bool true OpenWith -bool true Privileges -bool true"
# /finder ----------------------------------------------------------------- }}}
