---
# googlechrome ------------------------------------------------------------ {{{
- name: Allow installing user scripts via GitHub Gist or Userscripts.org
  command: "{{ item }}"
  with_items:
    - "defaults write com.google.Chrome ExtensionInstallSources -array 'https://gist.githubusercontent.com/' 'http://userscripts.org/*'"
    - "defaults write com.google.Chrome.canary ExtensionInstallSources -array 'https://gist.githubusercontent.com/' 'http://userscripts.org/*'"

- name: Disable the all too sensitive backswipe on trackpads
  command: "{{ item }}"
  with_items:
    - "defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false"
    - "defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false"

- name: Disable the all too sensitive backswipe on Magic Mouse
  command: "{{ item }}"
  with_items:
    - "defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false"
    - "defaults write com.google.Chrome.canary AppleEnableMouseSwipeNavigateWithScrolls -bool false"

- name: Use the system-native print preview dialog
  command: "{{ item }}"
  with_items:
    - "defaults write com.google.Chrome DisablePrintPreview -bool true"
    - "defaults write com.google.Chrome.canary DisablePrintPreview -bool true"

- name: Expand the print dialog by default
  command: "{{ item }}"
  with_items:
    - "defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true"
    - "defaults write com.google.Chrome.canary PMPrintingExpandedStateForPrint2 -bool true"
# /googlechrome ----------------------------------------------------------- }}}
