---
# safari ------------------------------------------------------------------ {{{
- name: Privacy - don’t send search queries to Apple
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.Safari UniversalSearchEnabled -bool false"
    - "defaults write com.apple.Safari SuppressSearchSuggestions -bool true"

- name: Press Tab to highlight each item on a web page
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true"
    - "defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true"

- name: Show the full URL in the address bar (note - this still hides the scheme)
  command: "defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true"

- name: Set Safari’s home page to `about:blank` for faster loading
  command: "defaults write com.apple.Safari HomePage -string 'about:blank'"

- name: Prevent Safari from opening ‘safe’ files automatically after downloading
  command: "defaults write com.apple.Safari AutoOpenSafeDownloads -bool false"

- name: Allow hitting the Backspace key to go to the previous page in history
  command: "defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true"

- name: Hide Safari’s bookmarks bar by default
  command: "defaults write com.apple.Safari ShowFavoritesBar -bool false"

- name: Hide Safari’s sidebar in Top Sites
  command: "defaults write com.apple.Safari ShowSidebarInTopSites -bool false"

- name: Disable Safari’s thumbnail cache for History and Top Sites
  command: "defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2"

- name: Enable Safari’s debug menu
  command: "defaults write com.apple.Safari IncludeInternalDebugMenu -bool true"

- name: Make Safari’s search banners default to Contains instead of Starts With
  command: "defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false"

- name: Remove useless icons from Safari’s bookmarks bar
  command: "defaults write com.apple.Safari ProxiesInBookmarksBar '()'"

- name: Enable the Develop menu and the Web Inspector in Safari
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.Safari IncludeDevelopMenu -bool true"
    - "defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true"
    - "defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true"

- name: Add a context menu item for showing the Web Inspector in web views
  command: "defaults write NSGlobalDomain WebKitDeveloperExtras -bool true"

# /safari ----------------------------------------------------------------- }}}
