---
# spotlight --------------------------------------------------------------- {{{
- name: Hide Spotlight tray-icon (and subsequent helper)
  shell: "sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search"

# Use `sudo mdutil -i off '/Volumes/foo'` to stop indexing any volume.
- name: Disable Spotlight indexing for any volume that gets mounted and has not yet been indexed before.
  shell: "sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array '/Volumes'"

# Yosemite-specific search results (remove them if your are using OS X 10.9 or older):
# MENU_DEFINITION
# MENU_CONVERSION
# MENU_EXPRESSION
# MENU_SPOTLIGHT_SUGGESTIONS (send search queries to Apple)
# MENU_WEBSEARCH             (send search queries to Apple)
# MENU_OTHER
- name: Change indexing order and disable some search results
  command: >
    defaults write com.apple.spotlight orderedItems -array
    '{"enabled" = 1;"name" = "APPLICATIONS";}'
    '{"enabled" = 1;"name" = "SYSTEM_PREFS";}'
    '{"enabled" = 1;"name" = "DIRECTORIES";}'
    '{"enabled" = 1;"name" = "PDF";}'
    '{"enabled" = 1;"name" = "FONTS";}'
    '{"enabled" = 0;"name" = "DOCUMENTS";}'
    '{"enabled" = 0;"name" = "MESSAGES";}'
    '{"enabled" = 0;"name" = "CONTACT";}'
    '{"enabled" = 0;"name" = "EVENT_TODO";}'
    '{"enabled" = 0;"name" = "IMAGES";}'
    '{"enabled" = 0;"name" = "BOOKMARKS";}'
    '{"enabled" = 0;"name" = "MUSIC";}'
    '{"enabled" = 0;"name" = "MOVIES";}'
    '{"enabled" = 0;"name" = "PRESENTATIONS";}'
    '{"enabled" = 0;"name" = "SPREADSHEETS";}'
    '{"enabled" = 0;"name" = "SOURCE";}'
    '{"enabled" = 0;"name" = "MENU_DEFINITION";}'
    '{"enabled" = 0;"name" = "MENU_OTHER";}'
    '{"enabled" = 0;"name" = "MENU_CONVERSION";}'
    '{"enabled" = 0;"name" = "MENU_EXPRESSION";}'
    '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}'
    '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'

- name: Load new settings before rebuilding the index
  shell: "sudo killall mds > /dev/null 2>&1"

- name: Make sure indexing is enabled for the main volume
  shell: "sudo mdutil -i on / > /dev/null"

- name: Rebuild the index from scratch
  shell: "sudo mdutil -E / > /dev/null"
# /spotlight -------------------------------------------------------------- }}}
