---
# utils ------------------------------------------------------------------- {{{
- name: Enable the debug menu in Address Book
  command: "defaults write com.apple.addressbook ABShowDebugMenu -bool true"

- name: Enable Dashboard dev mode (allows keeping widgets on the desktop)
  command: "defaults write com.apple.dashboard devmode -bool true"

- name: Enable the debug menu in iCal (pre-10.8)
  command: "defaults write com.apple.iCal IncludeDebugMenu -bool true"

- name: Use plain text mode for new TextEdit documents
  command: "defaults write com.apple.TextEdit RichText -int 0"

- name: Open and save files as UTF-8 in TextEdit
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.TextEdit PlainTextEncoding -int 4"
    - "defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4"

- name: Enable the debug menu in Disk Utility
  command: "{{ item }}"
  with_items:
    - "defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true"
    - "defaults write com.apple.DiskUtility advanced-image-options -bool true"
# /utils ------------------------------------------------------------------ }}}
